#!/bin/bash
# lancement : ./timefonction > times/timepdbSANS.txt
i=0

n=50

start=`date '+%s'`
while [ $i -le $n ]
do
    startu=`date '+%s'`
    i=$(($i + 1))
    python core.py > /dev/null #python core.py
    echo "$((`date '+%s'` - $startu))"
done


echo "Total time  $((`date '+%s'` - $start)) second(s)"

exit 0


